trigger:
- none

schedules:
  - cron: "0 18 * * 5"
    displayName: Weekly Friday snyc AZDO to GitHub
    branches:
      include:
      - main
    always: true

pool:
  vmImage: 'ubuntu-20.04'

variables:
- group: GitMirror

stages:
- stage: Mirror
  jobs:
  - job: Mirror
    workspace:
      clean: all
    steps:
    - bash: |
        set -e
        ./git_mirror.sh $(pat-source) $(pat-destination)
      displayName: Run Mirror Script
      failOnStderr: false
